'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DetailInput
    
    '''<summary>
    '''LotNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LotNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLotNo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLotNo2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLotNo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLotNo3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLotNo4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLotNo4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLotNo5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLotNo5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLotNo6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLotNo6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLotNo7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLotNo7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLotNo8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLotNo8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLotNo9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLotNo9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLotNo10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLotNo10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLotNo11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLotNo11 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLotNo12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLotNo12 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLotNo13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLotNo13 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLotNo14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLotNo14 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLotNo15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLotNo15 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtLotNo16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLotNo16 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPackage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackage As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDevice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDevice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Machine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Machine As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Process control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Process As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Program control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Program As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LotStartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LotStartTime As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''WaferLotNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WaferLotNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''MarkNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MarkNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TestFlow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestFlow As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TesterName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TesterName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TestBoxName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestBoxName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FinalYield control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FinalYield As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''WaferNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WaferNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ShipmentDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipmentDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Mode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Mode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Input control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Input As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RadioButton10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButton10 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButton11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButton11 As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''lblerror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerror As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
