'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DetailInputBin19
    
    '''<summary>
    '''LotNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LotNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Process control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Process As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Package control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Package As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Device control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Device As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtBIN19_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBIN19_1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTester1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTester1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Input1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Input1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtBIN19_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBIN19_2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTester2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTester2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Input2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Input2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtBIN19_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBIN19_3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTester3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTester3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Input3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Input3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblerror control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblerror As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
