'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DetailIssueNoICBrun
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DeviceTypeText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeviceTypeText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownList3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList3 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''OtherValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OtherValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtWafer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWafer As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''OSCheckText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSCheckText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OSCheckValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSCheckValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LotstatusText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LotstatusText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LotstatusValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LotstatusValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TesterNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TesterNoText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TesterNoValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TesterNoValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BoxNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BoxNoText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BoxNoValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BoxNoValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''OSTesterAnalysisText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSTesterAnalysisText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownList2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownList2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''OSTText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSTText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LV1PINText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LV1PINText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ME1PINTText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ME1PINTText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''round1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents round1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OSTTValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSTTValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LV1PINTValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LV1PINTValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ME1PINTValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ME1PINTValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''round2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents round2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OSTTValue0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSTTValue0 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LV1PINTValue0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LV1PINTValue0 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ME1PINTValue0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ME1PINTValue0 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''round3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents round3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OSTTValue1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSTTValue1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LV1PINTValue1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LV1PINTValue1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ME1PINTValue1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ME1PINTValue1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''round4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents round4 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OSTTValue2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSTTValue2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LV1PINTValue2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LV1PINTValue2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ME1PINTValue2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ME1PINTValue2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''round5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents round5 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OSTTValue3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSTTValue3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LV1PINTValue3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LV1PINTValue3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ME1PINTValue3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ME1PINTValue3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''round6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents round6 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OSTTValue4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSTTValue4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LV1PINTValue4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LV1PINTValue4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ME1PINTValue4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ME1PINTValue4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''InputButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InputButton As Global.System.Web.UI.WebControls.Button
End Class
