'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DetailOutICBurn
    
    '''<summary>
    '''OSCheckText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSCheckText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OSCheckValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSCheckValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TesterNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TesterNoText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''TesterNoValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TesterNoValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LotstatusText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LotstatusText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LotstatusValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LotstatusValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BoxNoText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BoxNoText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BoxNoValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BoxNoValue As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''GoodProductText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GoodProductText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GoodProductSHIP1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GoodProductSHIP1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''GoodProductSCRAP1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GoodProductSCRAP1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''DeviceText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeviceText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DeviceGoodcheck1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeviceGoodcheck1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''DeviceGoodRadioButtontextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeviceGoodRadioButtontextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DeviceNGcheck1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeviceNGcheck1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''DeviceNGRadioButtontextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeviceNGRadioButtontextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FinishedCB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FinishedCB As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''NgProductText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NgProductText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''NgProductBBANK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NgProductBBANK1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''NgProductSCRAP1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NgProductSCRAP1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''NgProducttime1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NgProducttime1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''OSTText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSTText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''LV1PINText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LV1PINText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ME1PINTText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ME1PINTText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Round1text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Round1text As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OSTTValue1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSTTValue1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LV1PINTValue1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LV1PINTValue1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ME1PINTValue1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ME1PINTValue1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Round2Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Round2Text As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OSTTValue2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSTTValue2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LV1PINTValue2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LV1PINTValue2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ME1PINTValue2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ME1PINTValue2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Round3Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Round3Text As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OSTTValue3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSTTValue3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LV1PINTValue3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LV1PINTValue3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ME1PINTValue3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ME1PINTValue3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Round4Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Round4Text As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OSTTValue4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSTTValue4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LV1PINTValue4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LV1PINTValue4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ME1PINTValue4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ME1PINTValue4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Round5Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Round5Text As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OSTTValue5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSTTValue5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LV1PINTValue5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LV1PINTValue5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ME1PINTValue5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ME1PINTValue5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Round6Text control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Round6Text As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OSTTValue6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OSTTValue6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LV1PINTValue6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LV1PINTValue6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ME1PINTValue6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ME1PINTValue6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''InputButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InputButton As Global.System.Web.UI.WebControls.Button
End Class
