'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DetailOutLowYield
    
    '''<summary>
    '''lblIssueNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIssueNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''btnUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpload As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''GridView2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView2 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''GoodProductText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GoodProductText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''GoodProductSHIP1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GoodProductSHIP1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''GoodProductSCRAP1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GoodProductSCRAP1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CauseText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CauseText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Cause1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cause1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Cause2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cause2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Cause3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cause3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Cause4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cause4 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Cause5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cause5 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Cause6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cause6 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''Cause7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cause7 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''NgProductText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NgProductText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''NgProductBBANK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NgProductBBANK1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''NgProductSCRAP1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NgProductSCRAP1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''NgProducttime1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NgProducttime1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''FnDateText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FnDateText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''FNDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FNDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DeviceText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeviceText As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DeviceGoodcheck1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeviceGoodcheck1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''DeviceGoodRadioButtontextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeviceGoodRadioButtontextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''DeviceNGcheck1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeviceNGcheck1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''DeviceNGRadioButtontextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeviceNGRadioButtontextbox As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''InputButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InputButton As Global.System.Web.UI.WebControls.Button
End Class
